### ISSUE TITLE
Conversion to .net core

### ISSUE THREAD

**Issue by JimmyHannon** [AkkaNetContrib/Akka.Persistence.PostgreSql#35]
Hi, I have converted this package to .net core (.NET Standard 1.6) locally. I know you have planned this conversion but maybe i can contribute. Do you want my help on this?

**Comment by Aaronontheweb** [comment]
@JimmyHannon yes! that would be much appreciated. Could you please send a PR?

**Comment by JimmyHannon** [comment]
@Aaronontheweb Is there another repo i can look at to see the basic solution setup for the .net core packages?

**Comment by Aaronontheweb** [comment]
@JimmyHannon myself and another contributor are in the process of converting https://github.com/akkadotnet/Akka.Persistence.SqlServer/pull/73 to .NET Standard and we're just about done with it there. Still working on getting the Docker CI stuff to work.

You can also check out this template I created here: https://github.com/petabridge/petabridge-dotnet-new - the work I've done with the build script on that Akka.Persistence.SqlServer PR is adapted from that.

**Comment by ncthbrt** [comment]
Any progress on this issue?

**Comment by JimmyHannon** [comment]
I have made a [PR#37](https://github.com/AkkaNetContrib/Akka.Persistence.PostgreSql/pull/37)

**Comment by alfredherr** [comment]
Any ETA on getting this to run on Core?

**Comment by JimmyHannon** [comment]
Closing this issue since package v1.3.1 has been released.
