### ISSUE TITLE
Upgrade to Akka v1.3.1

### ISSUE THREAD

**Issue by heynickc** [AkkaNetContrib/Akka.Persistence.PostgreSql#38]
Upgrade to Akka v1.3.1

**Comment by JimmyHannon** [comment]
Part of the work to support the SerializerWithStringManifest [()](PR #40) was the upgrade to 1.3.1
I hope we've not done double work...

**Comment by heynickc** [comment]
@JimmyHannon No we haven't, thanks for your help. I'm looking at your PR now
