### ISSUE TITLE
JSON serialization needs adjusting

### ISSUE THREAD

**Issue by sillyotter** [AkkaNetContrib/Akka.Persistence.PostgreSql#51]
I've been working on a shareded cluster app that uses postgresql for its persistence store.  I tried to use jsonb (or json) as my store-as setting.  When I do so, i get an error about it not being able to store the objects used by the sharding engine as they contain self references in their structure.  

It is possible to tell the newtonsoft json serializer to deal with references and structural loops like that with some settings, but so far I haven't found a way to override what the json serializers settings.

Would it be possible to expose such, or perhaps just easier to default the serializer to handling self references correctly?

**Comment by Horusiath** [comment]
Sharding messages have their custom binary serializers. Why do you store sharding journal as **jsonb**? Isn't better to simply keep a separate table for sharding purposes and use **bytea** there (see [example](https://petabridge.com/blog/introduction-to-cluster-sharding-akkadotnet))?

**Comment by sillyotter** [comment]
I should add that in addition to the sharding data being serialized, i am also using regular persistent objects as well, and I'd like to be able to query them directly.  At least with the config I have, the sharding engine is using the same persistence engine as my regular persistence objects.  Now that you mention it, I have a vague recollection of a way to configure different persistence engines for different parts of the system, but I cant find any references to it.

**Comment by sillyotter** [comment]
And now I see your example, and know where I saw the ability to configure different engines differently. :) thanks for the pointers.
